# Generated by Django 5.0.1 on 2024-02-12 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_newlisting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newlisting',
            name='image',
        ),
    ]
