# Generated by Django 5.0.1 on 2024-02-14 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_newlisting_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='newlisting',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
